export const postgresTables = [
  { table: "profiles", label: "Accounts and profile identity", key: "id" },
  { table: "auth_sessions", label: "HTTP-only login sessions", key: "id" },
  { table: "organizations", label: "Employer and organization records", key: "id" },
  { table: "role_memberships", label: "Role memberships", key: "id" },
  { table: "learner_profiles", label: "Learner onboarding profiles", key: "id" },
  { table: "mentor_profiles", label: "Mentor profiles", key: "id" },
  { table: "mentor_applications", label: "Mentor applications", key: "id" },
  { table: "leads", label: "Lead capture and assessment contacts", key: "id" },
  { table: "plans", label: "Subscription plans", key: "id" },
  { table: "courses", label: "Course catalogue", key: "id" },
  { table: "project_briefs", label: "Project briefs", key: "id" },
  { table: "enrollments", label: "Learner course enrollments", key: "id" },
  { table: "mentor_match_requests", label: "Mentor matching requests", key: "id" },
  { table: "mentor_sessions", label: "Mentor session bookings", key: "id" },
  { table: "assessment_attempts", label: "Assessment attempts", key: "id" },
  { table: "purchases", label: "Verified checkout purchases", key: "id" },
  { table: "mentor_project_proposals", label: "Mentor project proposals", key: "id" },
  { table: "mentor_credits", label: "Mentor review credits", key: "id" },
  { table: "subscriptions", label: "Billing subscriptions", key: "id" },
  { table: "project_submissions", label: "Learner project submissions", key: "id" },
  { table: "project_reviews", label: "Mentor project reviews", key: "id" },
  { table: "employer_shortlists", label: "Employer project shortlists", key: "id" },
  { table: "paystack_events", label: "Payment events", key: "id" },
  { table: "consultations", label: "Consultation requests", key: "id" },
  { table: "email_logs", label: "Transactional email log", key: "id" },
  { table: "site_settings", label: "Admin site settings", key: "key" },
  { table: "admin_audit_logs", label: "Admin audit logs", key: "id" },
  { table: "ai_token_wallets", label: "AI token wallets", key: "user_id" },
  { table: "ai_usage_events", label: "AI usage events", key: "id" },
  { table: "synthetic_dataset_jobs", label: "Synthetic dataset jobs", key: "id" },
  { table: "uploaded_datasets", label: "Uploaded learner datasets", key: "id" },
  { table: "ai_walkthroughs", label: "AI walkthrough jobs", key: "id" }
];
