insert into public.plans (code, role, name, price_kes, interval, paystack_plan_code, is_active, features)
values
  ('student-core', 'learner', 'Student Core', 2500, 'monthly', 'UA_STUDENT_CORE', true, '["Mentor matching", "Project briefs", "Review submissions", "Starter AI credits"]'::jsonb),
  ('data-ai-mentorship-cohort-2', 'learner', 'Data & AI Mentorship Cohort 2', 999, 'one-time', 'UA_DATA_AI_MENTORSHIP_COHORT_2', true, '["12-week mentorship", "Starts 3rd August 2026", "10 slots only", "Project review"]'::jsonb),
  ('mentor-booking', 'learner', 'Mentor Booking', 12500, 'one-time', 'UA_MENTOR_BOOKING', true, '["Mentor matching", "Project access", "Review rhythm", "Guided growth plan"]'::jsonb),
  ('student-plus', 'learner', 'Student Plus', 5500, 'monthly', 'UA_STUDENT_PLUS', true, '["Weekly mentor sessions", "Priority reviews", "More AI data credits", "Proof profile"]'::jsonb),
  ('mentor-pro', 'mentor', 'Mentor Pro', 2500, 'monthly', 'UA_MENTOR_PRO', true, '["Review queue", "Learner management", "Payout tracking", "Reputation profile"]'::jsonb),
  ('ai-data-builder', 'learner', 'AI Data Builder', 1800, 'monthly', 'UA_AI_DATA_BUILDER', true, '["Synthetic data generation", "Dataset walkthroughs", "CSV export", "Usage recommendations"]'::jsonb),
  ('course-pass', 'course', 'Course Pass', 5000, 'one-time', 'UA_COURSE_PASS', true, '["One pathway", "Project files", "Mentor intro", "Certificate review"]'::jsonb),
  ('employer-scout', 'employer', 'Employer Scout', 50000, 'monthly', 'UA_EMPLOYER_SCOUT', true, '["Verified learner search", "Shortlists", "Intro requests", "Proof review"]'::jsonb)
on conflict (code) do update set
  role = excluded.role,
  name = excluded.name,
  price_kes = excluded.price_kes,
  interval = excluded.interval,
  paystack_plan_code = excluded.paystack_plan_code,
  is_active = excluded.is_active,
  features = excluded.features;

insert into public.courses (
  slug,
  title,
  category,
  course_type,
  level,
  duration,
  price_kes,
  summary,
  start_date,
  display_order,
  is_active,
  metadata
)
values
  (
    'working-with-data-for-professionals',
    'Working with Data for Professionals',
    'Business',
    'course',
    'Foundation',
    '6 weeks',
    10000,
    'A practical course for professionals who handle reports, spreadsheets, dashboards, and AI-generated answers without trying to become technical analysts.',
    '2026-07-06',
    5,
    true,
    '{"instructor":"Ezra Muinde","instructor_title":"Senior Data Scientist and AI Engineer","schedule":"Classes start 6th July.","modules":["Data confidence","Spreadsheet thinking","Dashboard reading","AI-assisted analysis","Decision communication"],"outcomes":["Read reports with confidence","Ask sharper business questions","Turn data and AI outputs into decisions"],"tools":["Excel","Dashboards","AI assistants","Reports"],"projects":["Weekly business scorecard","Insight memo","Dashboard interpretation exercise"],"roles":["Manager","Operations lead","Finance officer","Program officer"],"demand":["SMEs","NGOs","Operations","Leadership"]}'::jsonb
  ),
  (
    'excel-workshop',
    'Data Thinking with Excel',
    'Data',
    'workshop',
    'Foundation',
    '3 months',
    12500,
    'Structure business problems, model decisions, and communicate insight with Excel before moving into BI or AI.',
    '2026-06-20',
    10,
    true,
    '{"instructor":"Ezra Muinde","instructor_title":"Senior Data Scientist and AI Engineer","modules":["Excel structure","Formulas and logic","Pivot tables","Scenario analysis","Dashboard storytelling"],"outcomes":["Build reliable workbooks","Read business data with confidence","Create board-ready Excel dashboards"],"tools":["Excel","Power Query","PivotTables","CSV"],"projects":["Safaricom Subscriber Tracker","M-Pesa Revenue Analyser","KCB Loan Portfolio Analyser"],"roles":["Operations analyst","Finance assistant","Business analyst"],"demand":["SMEs","Banking","Telecom","Retail"]}'::jsonb
  ),
  (
    'powerbi-workshop',
    'Business Analytics with Power BI',
    'BI',
    'workshop',
    'Core',
    '3 months',
    15000,
    'Turn raw data into decision-ready dashboards, DAX measures, and reporting systems leaders can actually use.',
    '2026-05-04',
    20,
    true,
    '{"instructor":"Jacktone Etemesi","instructor_title":"Senior Data Scientist","modules":["Power Query","Star schema models","DAX measures","Report design","Refresh and sharing"],"outcomes":["Model clean BI data","Build executive dashboards","Explain trends and KPI movement"],"tools":["Power BI","DAX","Power Query","Excel"],"projects":["Retail Sales Performance Report","Financial P&L Dashboard","Logistics KPI Tracker"],"roles":["BI analyst","Reporting analyst","Operations analyst"],"demand":["Finance","Logistics","Retail","Operations"]}'::jsonb
  ),
  (
    'ai-mastery',
    'AI Fluency for Business Leaders & Analysts',
    'AI',
    'mastery',
    'AI Mastery',
    '1 month',
    2500,
    'Understand where AI fits, where it fails, and how to use it safely in analysis, leadership, and day-to-day work.',
    '2026-05-04',
    30,
    true,
    '{"instructor":"Ezra Muinde","instructor_title":"Senior Data Scientist and AI Engineer","modules":["AI fundamentals","Prompting for business","Tool selection","AI risk","Decision workflows"],"outcomes":["Lead AI conversations","Use AI without exposing sensitive data","Turn AI outputs into usable decisions"],"tools":["AI assistants","Prompt frameworks","Reports","Spreadsheets"],"projects":["AI Tools Audit","Prompt Engineering Workbook","AI Strategy Memo"],"roles":["Manager","Analyst","Founder","Team lead"],"demand":["SMEs","NGOs","Analytics teams","Operations"]}'::jsonb
  ),
  (
    'ai-agents-masterclass',
    'Agentic Systems for Decision Automation',
    'AI',
    'masterclass',
    'Advanced',
    '1 month',
    5000,
    'Design AI agents that support analysis, monitoring, routing, and decision execution in real business environments.',
    '2026-07-07',
    40,
    true,
    '{"instructor":"Ezra Muinde","instructor_title":"Senior Data Scientist and AI Engineer","schedule":"Every Tuesday and Thursday evening for 1 hour 30 minutes across 8 sessions.","modules":["Agent design","n8n workflows","Webhooks and APIs","Memory and tools","Human review"],"outcomes":["Design workflow agents","Connect AI to business systems","Build guardrails for automation"],"tools":["n8n","OpenAI","Webhooks","APIs","JSON"],"projects":["Lead Qualification Agent","Document Summarisation Pipeline","Multi-Agent Research Assistant"],"roles":["AI builder","Automation analyst","Data product builder"],"demand":["Sales ops","Customer support","Finance","Research"]}'::jsonb
  ),
  (
    'python-for-analytics',
    'Python for Data Analytics',
    'Data',
    'course',
    'Intermediate',
    '6 weeks',
    10000,
    'Use Python to clean data, answer business questions, and produce project-ready analysis.',
    null,
    50,
    true,
    '{"instructor":"Jacktone Etemesi","instructor_title":"Senior Data Scientist","modules":["Python foundations","Pandas workflows","Charts and summaries","Business recommendations"],"outcomes":["Clean messy datasets","Build reproducible analysis","Present decisions with evidence"],"tools":["Python","Pandas","Jupyter","CSV"],"projects":["Product growth funnel","SME cashflow analysis"],"roles":["Data analyst","Operations analyst","BI analyst"],"demand":["Retail","Finance","SaaS"]}'::jsonb
  ),
  (
    'sql-for-analysts',
    'SQL for Analysts',
    'Data',
    'course',
    'Beginner',
    '4 weeks',
    3500,
    'Query real business data, join tables, and prepare datasets for dashboards and reports.',
    null,
    60,
    true,
    '{"instructor":"Jacktone Etemesi","instructor_title":"Senior Data Scientist","modules":["Selects and filters","Joins","Aggregations","Business reporting"],"outcomes":["Write clean SQL queries","Debug joins","Create analysis tables"],"tools":["SQL","PostgreSQL","Railway"],"projects":["Customer support quality","Nairobi FMCG sales recovery"],"roles":["Data analyst","Reporting analyst"],"demand":["Telecom","Payments","Logistics"]}'::jsonb
  ),
  (
    'data-fluency-for-operators-and-managers',
    'Working with Data for Professionals Who Are Not Technical Analysts',
    'Business',
    'course',
    'Beginner',
    '3 weeks',
    10000,
    'Read reports, ask better data questions, use AI safely, and turn everyday workplace data into decisions without becoming technical.',
    '2026-07-06',
    70,
    true,
    '{"instructor":"Ezra Muinde","instructor_title":"Senior Data Scientist and AI Engineer","schedule":"Classes start 6th July.","modules":["Business questions","Metric definitions","Dashboard reading","Data quality traps","AI-assisted summaries"],"outcomes":["Read dashboards with confidence","Spot weak metrics and quality issues","Turn reports into practical next steps"],"tools":["Excel","Dashboards","AI assistants","Reports"],"projects":["Weekly business scorecard","Manager-ready insight memo"],"roles":["Operations manager","Sales lead","Finance assistant","Program officer"],"demand":["SMEs","NGOs","Operations","Customer support"]}'::jsonb
  )
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  course_type = excluded.course_type,
  level = excluded.level,
  duration = excluded.duration,
  price_kes = excluded.price_kes,
  summary = excluded.summary,
  start_date = excluded.start_date,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  metadata = excluded.metadata;

insert into public.project_briefs (
  slug,
  track,
  source_project_id,
  title,
  company_context,
  company_tag,
  level,
  estimated_time,
  skills,
  learning_outcome,
  data_source,
  summary,
  dataset_path,
  walkthrough_path,
  task_path,
  rubric,
  deliverables,
  score_bands,
  feedback,
  display_order,
  is_active,
  metadata
)
values
  ('safaricom-subscriber-tracker','excel','ex-01','Safaricom Subscriber Tracker','Safaricom PLC','NSE: SCOM','Beginner','3-4 hrs','{"Excel navigation","SUM and AVERAGE","Cell formatting","Bar and line charts"}','Structure real business data and produce a chart-ready subscriber report.','Safaricom annual reports','Build a clean workbook tracking subscribers, M-Pesa users, fibre, and revenue per user.',null,null,null,'["Data structure","Formula accuracy","Chart clarity","Business interpretation"]'::jsonb,'["Formatted workbook","Subscriber trend chart","One-page insight summary"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',1,true,'{"lessons":"Lessons 1-8"}'::jsonb),
  ('mpesa-revenue-analyser','excel','ex-02','M-Pesa Revenue Analyser','M-Pesa / Safaricom','M-Pesa Africa','Intermediate','4-5 hrs','{"IF logic","XLOOKUP","Conditional formatting","Combo charts"}','Build a logic-driven Excel model that explains revenue movement.','M-Pesa segment disclosures','Identify top revenue categories and weaker agent tiers using logic, lookups, and charts.',null,null,null,'["Lookup accuracy","Risk flags","Chart quality","Recommendation quality"]'::jsonb,'["Revenue model","Flagged agent tiers","Dashboard summary"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',2,true,'{"lessons":"Lessons 9-12"}'::jsonb),
  ('kcb-loan-portfolio-analyser','excel','ex-03','KCB Loan Portfolio Analyser','KCB Group PLC','NSE: KCB','Intermediate','5-6 hrs','{"Pivot tables","Calculated fields","Data validation","Workbook protection"}','Use pivot tables to summarize a loan book and highlight portfolio risk.','KCB annual reports','Build a pivot-table model with calculated fields, NPL ratios, and a protected executive summary.',null,null,null,'["Pivot design","Ratio accuracy","Risk interpretation","Professional formatting"]'::jsonb,'["Pivot model","NPL summary","Executive sheet"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',3,true,'{"lessons":"Lessons 13-16"}'::jsonb),
  ('equity-bank-branch-performance-model','excel','ex-04','Equity Bank Branch Performance Model','Equity Group Holdings','NSE: EQTY','Advanced','6-7 hrs','{"INDEX/MATCH","Dynamic arrays","Power Query","Slicers"}','Build an interactive branch performance report for managers.','Equity Group reports','Create a branch ranking model with dynamic arrays, lookup logic, and country-level slicers.',null,null,null,'["Model logic","Interactivity","Data cleaning","Decision usefulness"]'::jsonb,'["Branch ranking model","Country slicers","Management notes"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',4,true,'{"lessons":"Lessons 17-19"}'::jsonb),
  ('kenya-airways-route-profitability-dashboard','excel','ex-05','Kenya Airways Route Profitability Dashboard','Kenya Airways PLC','NSE: KQ','Advanced','7-9 hrs','{"Scenario Manager","Goal Seek","Named ranges","Dashboard design"}','Create a board-ready workbook for scenario planning.','Kenya Airways investor materials','Model fuel-cost scenarios, break-even load factors, and a dynamic route profitability dashboard.',null,null,null,'["Scenario logic","Dashboard usability","Financial reasoning","Narrative clarity"]'::jsonb,'["Scenario model","Route dashboard","Break-even memo"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',5,true,'{"lessons":"Lessons 20-24"}'::jsonb),
  ('retail-sales-performance-report','powerbi','pbi-01','Retail Sales Performance Report','Duka Fresh','Kenyan Market','Beginner','4-5 hrs','{"Power Query","Star schema","Basic DAX","Date tables"}','Build a clean executive report from retail transactions.','Synthetic Kenyan retail dataset','Connect retail data, build a star schema, and create an executive report with MTD, QTD, and YTD comparisons.',null,null,null,'["Model structure","DAX accuracy","Visual clarity","Executive usefulness"]'::jsonb,'["Data model","Sales dashboard","Executive summary"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',1,true,'{"lessons":"Lessons 1-4"}'::jsonb),
  ('financial-pl-dashboard','powerbi','pbi-02','Financial P&L Dashboard','Jua Kali Finance','Kenyan Market','Intermediate','5-7 hrs','{"DAX time intelligence","Drill-through","Bookmarks","Dynamic titles"}','Deliver a finance-grade P&L report in Power BI.','Synthetic P&L dataset','Model a profit and loss report with drill-through pages, dynamic titles, and time intelligence measures.',null,null,null,'["DAX quality","Navigation","Finance logic","Commentary"]'::jsonb,'["P&L report","Drill-through page","Variance commentary"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',2,true,'{"lessons":"Lessons 5-8"}'::jsonb),
  ('logistics-kpi-tracker','powerbi','pbi-03','Logistics KPI Tracker','Swift Delivery','Kenyan Market','Intermediate','5-6 hrs','{"Calculated columns","RLS","Maps","KPI visuals"}','Build an operations dashboard with location and performance signals.','Synthetic logistics dataset','Track on-time delivery rates, route efficiency, and driver performance across regions.',null,null,null,'["KPI definitions","Map clarity","RLS setup","Operational action"]'::jsonb,'["KPI dashboard","Region map","Driver performance notes"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',3,true,'{"lessons":"Lessons 9-12"}'::jsonb),
  ('customer-segmentation-report','powerbi','pbi-04','Customer Segmentation Report','Duka Smart','Kenyan Market','Advanced','7-9 hrs','{"Complex DAX","RFM modelling","Cohort analysis","What-if parameters"}','Build segmentation logic that supports targeted retention decisions.','Synthetic CRM dataset','Use RFM analysis to segment customers and build a churn-risk dashboard with cohort analysis.',null,null,null,'["Segmentation logic","DAX depth","Cohort clarity","Actionability"]'::jsonb,'["RFM model","Churn dashboard","Retention action list"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',4,true,'{"lessons":"Lessons 13-16"}'::jsonb),
  ('ai-tools-audit-for-your-role','ai-mastery','ai-01','AI Tools Audit for Your Role','Your Organisation','Any Industry','Beginner','2-3 hrs','{"AI tool evaluation","Business framing","ROI analysis","Risk assessment"}','Build a clear tool evaluation framework for any role.','No dataset required','Map 10 AI tools relevant to a real job function, then evaluate capability, risk, and ROI.',null,null,null,'["Tool fit","Risk thinking","Business clarity","Recommendation strength"]'::jsonb,'["Tool map","Risk notes","ROI recommendation"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',1,true,'{"lessons":"Modules 1-2"}'::jsonb),
  ('prompt-engineering-workbook','ai-mastery','ai-02','Prompt Engineering Workbook','Cross-Industry','Any Role','Beginner','3-4 hrs','{"Prompt engineering","Role prompting","Output structuring","Evaluation"}','Write prompts that produce consistent professional outputs.','No dataset required','Complete structured prompting challenges across marketing, finance, HR, and operations.',null,null,null,'["Prompt clarity","Output quality","Iteration","Usefulness"]'::jsonb,'["Prompt workbook","Before/after outputs","Evaluation notes"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',2,true,'{"lessons":"Modules 3-4"}'::jsonb),
  ('ai-strategy-memo','ai-mastery','ai-03','AI Strategy Memo','Fictional East African Company','East Africa','Intermediate','4-5 hrs','{"Strategic thinking","AI ethics","Business writing","Use-case design"}','Advise leaders on AI adoption without overselling or exposing sensitive data.','No dataset required','Write a concise AI adoption memo identifying high-impact use cases, risks, and rollout guardrails.',null,null,null,'["Strategic clarity","Risk control","Feasibility","Writing quality"]'::jsonb,'["Strategy memo","Risk register","Use-case shortlist"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',3,true,'{"lessons":"Modules 5-6"}'::jsonb),
  ('lead-qualification-agent','ai-agents','ag-01','Lead Qualification Agent','n8n + OpenAI','Automation','Intermediate','4-6 hrs','{"n8n workflows","Webhooks","OpenAI API","CRM routing"}','Ship a working AI agent that automates a sales process.','Workflow brief','Build a workflow that captures leads, scores them with AI, and routes qualified leads to a CRM.',null,null,null,'["Workflow logic","Scoring quality","Guardrails","Business fit"]'::jsonb,'["Workflow map","Scoring prompt","Handoff notes"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',1,true,'{"lessons":"Modules 1-2"}'::jsonb),
  ('document-summarisation-pipeline','ai-agents','ag-02','Document Summarisation Pipeline','LangChain + Email','Automation','Intermediate','5-7 hrs','{"PDF parsing","Prompt chaining","Email automation","Quality checks"}','Build a document intelligence flow that saves manual reading time.','Sample PDF documents','Create a pipeline that reads uploaded documents, extracts key insights, and sends a structured summary.',null,null,null,'["Extraction quality","Summary clarity","Automation flow","Reliability"]'::jsonb,'["Pipeline design","Summary output","Error handling notes"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',2,true,'{"lessons":"Modules 3-4"}'::jsonb),
  ('multi-agent-research-assistant','ai-agents','ag-03','Multi-Agent Research Assistant','CrewAI','Agentic Systems','Advanced','7-9 hrs','{"Agent roles","Task chaining","Tool use","Output formatting"}','Orchestrate multiple AI agents into one business research workflow.','No dataset required','Design a researcher, analyst, and writer agent system that produces business reports with review checkpoints.',null,null,null,'["Agent boundaries","Task sequence","Output quality","Human review"]'::jsonb,'["Agent map","Workflow run","Report sample"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',3,true,'{"lessons":"Modules 5-6"}'::jsonb),
  ('customer-support-bot','ai-agents','ag-04','Customer Support Bot','OpenAI Assistants','Deployment','Advanced','8-10 hrs','{"RAG","Memory","Support workflows","Deployment"}','Design a production-aware AI support assistant with safe handoff.','Sample knowledge base','Build a knowledge-based support bot with retrieval, memory, and handoff logic.',null,null,null,'["Retrieval quality","Conversation safety","Handoff clarity","Deployment readiness"]'::jsonb,'["Bot design","Test transcript","Handoff policy"]'::jsonb,'["90-100: portfolio-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors review the submission for technical accuracy, business reasoning, and manager-ready communication.',4,true,'{"lessons":"Modules 7-8"}'::jsonb),
  ('nairobi-fmcg-sales-recovery','practice-labs','lab-01','Nairobi FMCG Sales Recovery','RetailCo','Practice Lab','Intermediate','3-5 hrs','{"Trend analysis","Commercial reasoning","Recommendation writing"}','Turn a sales dataset into a recovery recommendation.','Synthetic FMCG dataset','Find the territories and product groups pulling sales down, then recommend a recovery plan.','/downloads/datasets/nairobi-fmcg-sales-recovery.csv','/downloads/walkthroughs/nairobi-fmcg-sales-recovery.md',null,'["Accuracy","Decision quality","Clarity","Business usefulness"]'::jsonb,'["Cleaned dataset","Trend analysis","Recovery recommendation"]'::jsonb,'["90-100: manager-ready","75-89: strong with revisions","60-74: needs coaching"]'::jsonb,'Mentors check whether the final recommendation is specific enough for a manager to act on.',1,true,'{"lessons":"Practice"}'::jsonb),
  ('sme-cashflow-collections','practice-labs','lab-02','SME Cashflow and Collections','FinanceCo','Practice Lab','Intermediate','3-5 hrs','{"Segmentation","Financial reasoning","Prioritization"}','Explain which customers to call first and why.','Synthetic receivables dataset','Prioritize overdue accounts and build a collections plan that protects cashflow.','/downloads/datasets/sme-cashflow-collections.csv','/downloads/walkthroughs/sme-cashflow-collections.md',null,'["Segmentation","Financial reasoning","Prioritization","Communication"]'::jsonb,'["Aging summary","Risk segmentation","Collections action list"]'::jsonb,'["90-100: finance-ready","75-89: good analysis","60-74: needs tighter logic"]'::jsonb,'The strongest submissions explain which customers to call first and why.',2,true,'{"lessons":"Practice"}'::jsonb),
  ('customer-support-quality','practice-labs','lab-03','Customer Support Quality','SupportCo','Practice Lab','Beginner','2-4 hrs','{"Data cleaning","Pattern finding","Operations recommendations"}','Connect quality metrics to team coaching actions.','Synthetic support dataset','Analyze support tickets, quality scores, and response patterns to improve service.','/downloads/datasets/customer-support-quality.csv','/downloads/walkthroughs/customer-support-quality.md',null,'["Data cleaning","Pattern finding","Recommendation quality","Presentation"]'::jsonb,'["Quality dashboard","Root cause analysis","Team coaching plan"]'::jsonb,'["90-100: operations-ready","75-89: strong signal","60-74: needs refinement"]'::jsonb,'Mentors look for clear coaching actions, not just ticket counts.',3,true,'{"lessons":"Practice"}'::jsonb),
  ('product-growth-funnel','practice-labs','lab-04','Product Growth Funnel','Analytics Co','Practice Lab','Intermediate','3-5 hrs','{"Funnels","Metric definitions","Experiment thinking"}','Tie funnel drop-off to one practical growth move.','Synthetic product dataset','Measure conversion across signup, activation, trial, and paid customer steps.','/downloads/datasets/product-growth-funnel.csv','/downloads/walkthroughs/product-growth-funnel.md',null,'["Metric accuracy","Experiment thinking","Narrative","Next-step clarity"]'::jsonb,'["Funnel table","Drop-off analysis","Growth experiment proposal"]'::jsonb,'["90-100: product-ready","75-89: strong readout","60-74: needs coaching"]'::jsonb,'Good submissions connect the funnel numbers to one clear growth move.',4,true,'{"lessons":"Practice"}'::jsonb)
on conflict (slug) do update set
  track = excluded.track,
  source_project_id = excluded.source_project_id,
  title = excluded.title,
  company_context = excluded.company_context,
  company_tag = excluded.company_tag,
  level = excluded.level,
  estimated_time = excluded.estimated_time,
  skills = excluded.skills,
  learning_outcome = excluded.learning_outcome,
  data_source = excluded.data_source,
  summary = excluded.summary,
  dataset_path = excluded.dataset_path,
  walkthrough_path = excluded.walkthrough_path,
  task_path = excluded.task_path,
  rubric = excluded.rubric,
  deliverables = excluded.deliverables,
  score_bands = excluded.score_bands,
  feedback = excluded.feedback,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  metadata = excluded.metadata;
